// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.CoinFlipper
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("total_flips")]
        public long TotalFlips { get; set; }

        [JsonProperty("flips")]
        public FirstFlip[] Flips { get; set; }

        [JsonProperty("heads_count")]
        public long HeadsCount { get; set; }

        [JsonProperty("tails_count")]
        public long TailsCount { get; set; }

        [JsonProperty("heads_percentage")]
        public long HeadsPercentage { get; set; }

        [JsonProperty("tails_percentage")]
        public long TailsPercentage { get; set; }

        [JsonProperty("longest_streak")]
        public LongestStreak LongestStreak { get; set; }

        [JsonProperty("first_flip")]
        public FirstFlip FirstFlip { get; set; }

        [JsonProperty("last_flip")]
        public FirstFlip LastFlip { get; set; }

        [JsonProperty("is_fair")]
        public bool IsFair { get; set; }
    }

    public partial class LongestStreak
    {
        [JsonProperty("length")]
        public long Length { get; set; }

        [JsonProperty("type")]
        public FirstFlip Type { get; set; }
    }

    public enum FirstFlip { Heads, Tails };
}
